trailingComma: "es5"
singleQuote: false
editorconfig: true
tailwindStylesheet: "./src/styles/global.css"
importOrderSideEffects: false
# importOrder: ["^@(.*)/.*$", "^[./]", "^@/lib/(.*)$", "^[./]"]
plugins:
   - "@trivago/prettier-plugin-sort-imports"
   - "prettier-plugin-astro"
   - "prettier-plugin-tailwindcss"
overrides:
   - files: "*.astro"
     options:
        parser: "astro"
